name: Textbox Validation

on:
  workflow_dispatch:

jobs:
  textbox_validation_job

  runs-on: ubuntu-latest

  steps:
    - name: Checkout Code
      uses: actions/checkout@v4
  
    - name: Set up Python
      uses: actions/setup-python@v5.1.1
      with:
        python-version: '3.12'
    
    - name: Create virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
        rfbrowser init
    
    - name: Run Robot Framework Tests
      run: |
        source venv/bin/activate
        robot --outputdir output/results example_test.robot
    
    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      with:
        name: robot-test-results
        path: output/results/