name: Test Suite Executed

on:
  workflow_dispatch:
    inputs:
      suite-name:
        description: 'Name of the test suite to run'
        required: true
        type: choice
        options:
          - textbox_validation
          - radioButton_validation
          - checkbox_validation


jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
    
      - name: Set up Python
        uses: actions/setup-python@v5.1.1
        with:
          python-version: '3.12'
      
      - name: Cache Python packages
        id: cache-python
        uses: actions/cache@v4.0.2
        with:
          path: |
            ~/.cache/pip
            venv
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Create virtual environment on Linux machine
        if: runner.os == 'Linux' 
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          rfbrowser init
          
      - name: Run Robot Framework Tests on Linux Machine
        if: runner.os == 'Linux' 
        run: |
          source venv/bin/activate
          robot --outputdir results "tests/${{ github.event.inputs.suite-name }}.robot"
        continue-on-error: false  # Continue even if this step fails
      
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4.3.6
        with:
          name: robot-${{ matrix.os }}-test-results
          path: |
            results/*